# Section 1:  NumPy Solutions

### Import the library with alias np

In [17]:
import numpy as np

####  1. Create an array of  8 eights

In [18]:
# Create an array of 8 eights using NumPy
np.ones(8)*8


array([8., 8., 8., 8., 8., 8., 8., 8.])

#### 2. Create an array of the integers from 10 to 50

In [19]:
# Create an array of integers from 10 to 50
integers_array = np.arange(10, 51)

print(integers_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### 3. Create a 3x3 matrix with values ranging from 22 to 30

In [20]:
arr = np.arange(22,31).reshape(3,3)
arr

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

## Indexing
Use below Array 'arr' for Questions below. 

arr = np.arange(26,51).reshape(5,5)



In [21]:
arr = np.arange(26,51).reshape(5,5)
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

#### 4. Use indexing on arr to get below output

       [[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]]

In [22]:
arr[2:,1:]

array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

#### 5. Use indexing on arr to get below output
Output should be 50

In [23]:
arr[4:,4][0]

50

#### 6. Use indexing on arr to get below output
      [[27],
       [32],
       [37]]

In [24]:
arr[0:3,1:2]

array([[27],
       [32],
       [37]])

#### 7. Use indexing on arr to get below output
      [46, 47, 48, 49, 50]

In [25]:
arr[-1]

array([46, 47, 48, 49, 50])

#### 8. Use indexing on arr to get below output
     [[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]]

In [29]:
rows_41_to_50 = matrix[1:3, :]
print("Rows [[41, 42, 43, 44, 45], [46, 47, 48, 49, 50]]:")
print(rows_41_to_50)

NameError: name 'matrix' is not defined

### NumPy  Stats Functions

Use below given array 'arr'

#### 9. Find the sum of all the values in given array 'arr'

In [30]:
import numpy as np

arr = np.array([[41, 42, 43, 44, 45],
                [46, 47, 48, 49, 50]])

# Find the sum of all the values in the array
arr_sum = np.sum(arr) 

print("Sum of all values in arr:", arr_sum)

Sum of all values in arr: 455


#### 10. Find the standard deviation of the values in given array 'arr'

In [31]:
arr_std = np.std(arr) 

print("Standard deviation of values in arr:", arr_std) 

Standard deviation of values in arr: 2.8722813232690143


#### 11.  Find the mean of all the values in given array 'arr'

In [32]:
arr_mean = np.mean(arr) 

print("Mean of all values in arr:", arr_mean) 


Mean of all values in arr: 45.5


# Section 2: Pandas Solutions

#### Import pandas library  with alias pd

In [33]:
import pandas as pd

#### Read the given csv file

In [34]:
df = pd.read_csv("C:\\Users\\SAHITHYA AAKULA\\OneDrive\\Desktop\\Data science case study\\case study2-python problems\\sales.csv")

### 1. What are the unique values in  the column "Parking"?

In [37]:
df["Parking"].unique()

array(['Open', 'Not Provided', 'Covered', 'No Parking'], dtype=object)

### 2. What is the mean store area of the given data? 

In [39]:
df["Store_Area"].mean()

1511.862554112554

### 3.What are the different columns available in the dataset?

In [40]:
df.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

### 4. Create a new series (series1) with only the values of third row

In [42]:
print("Columns in the dataset:", df.columns)


Columns in the dataset: Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')


### 5. Create a new dataframe(df_short which contain first 5 rows and two columns("Coupon_Category" and "Store_Sales")

In [43]:
series1 = df.iloc[2]
print("Third row values:", series1)

Third row values: Observation                        3
Dist_Taxi                    11001.0
Dist_Market                  14399.0
Dist_Metro                   16991.0
Store_Area                    1340.0
Items_Available               1609.0
Parking                 Not Provided
Coupon_Category                CAT A
Daily_Customer_Count             720
Store_Sales                    54010
Name: 2, dtype: object


### 6. In dataframe df_short, replace the index with ["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]

In [45]:
("Coupon_Category" and "Store_Sales")
df_short = df.head(5)[['Coupon_Category', 'Store_Sales']]
print("First 5 rows of df_short with 'Coupon_Category' and 'Store_Sales':\n", df_short)

First 5 rows of df_short with 'Coupon_Category' and 'Store_Sales':
   Coupon_Category  Store_Sales
0           CAT B        66490
1           CAT B        39820
2           CAT A        54010
3           CAT B        53730
4           CAT B        46620


### 7. Create a dataframe df2 fulfilling the given conditions - Dist_Metro>18000 and Parking= Open

In [46]:
 ["First Row", "Second Row", "Third Row", "Fourth Row", "Fifth Row"]
df_short.index = ["First Row", "Second Row", "Third Row", "Fourth Row", "Fifth Row"]
print("Updated df_short index:\n", df_short)

Updated df_short index:
            Coupon_Category  Store_Sales
First Row            CAT B        66490
Second Row           CAT B        39820
Third Row            CAT A        54010
Fourth Row           CAT B        53730
Fifth Row            CAT B        46620


### 8.What is the minimum store sales and the standard Deviation of store sales.

In [47]:
df2 = df[(df['Dist_Metro'] > 18000) & (df['Parking'] == 'Open')]
print("Dataframe df2 with conditions 'Dist_Metro > 18000' and 'Parking = Open':\n", df2)

Dataframe df2 with conditions 'Dist_Metro > 18000' and 'Parking = Open':
      Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
88            89    14306.0      12591.0     18029.0      1441.0   
218          219    11195.0      16650.0     18762.0      1406.0   
338          339     9308.0      18281.0     18532.0      1771.0   
742          743    12973.0      15178.0     18836.0      1542.0   
791          792    14470.0      14517.0     18178.0      1645.0   
930          931    15082.0      14700.0     19617.0      1299.0   

     Items_Available Parking Coupon_Category  Daily_Customer_Count  \
88            1723.0    Open           CAT B                   330   
218           1677.0    Open           CAT A                   480   
338           2147.0    Open           CAT C                   430   
742           1844.0    Open           CAT B                   680   
791           1963.0    Open           CAT C                   900   
930           1560.0    Open 

### 9. Group the dataset with respect to the variable 'Coupon_Category' using aggregation function mean()

In [50]:

grouped_by_coupon = df.groupby('Coupon_Category')['Store_Sales'].mean()
print("Mean Store Sales by Coupon_Category:\n", grouped_by_coupon)


Mean Store Sales by Coupon_Category:
 Coupon_Category
CAT A    73998.662614
CAT B    59191.479452
CAT C    45205.504202
Name: Store_Sales, dtype: float64


### 10. Drop the variable 'Parking' from the data.

In [52]:
df_no_parking = df.drop(columns=['Parking'])
print("Data without 'Parking' column:\n", df_no_parking.head())

Data without 'Parking' column:
    Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0            1     9796.0       5250.0     10703.0      1659.0   
1            2     8294.0       8186.0     12694.0      1461.0   
2            3    11001.0      14399.0     16991.0      1340.0   
3            4     8301.0      11188.0     12289.0      1451.0   
4            5    10510.0      12629.0     13921.0      1770.0   

   Items_Available Coupon_Category  Daily_Customer_Count  Store_Sales  
0           1961.0           CAT B                   530        66490  
1           1752.0           CAT B                   210        39820  
2           1609.0           CAT A                   720        54010  
3           1748.0           CAT B                   620        53730  
4           2111.0           CAT B                   450        46620  


### 11. Export the Q10 dataframe without the 'Parking' column into a csv file.

In [53]:
df_no_parking.to_csv('data_without_parking.csv', index=False)


# Question on some additional functions

###  Display the first 10 entries of the dataset.  (Hint-use function head())

In [54]:
print("First 10 entries:\n", df.head(10))

First 10 entries:
    Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0            1     9796.0       5250.0     10703.0      1659.0   
1            2     8294.0       8186.0     12694.0      1461.0   
2            3    11001.0      14399.0     16991.0      1340.0   
3            4     8301.0      11188.0     12289.0      1451.0   
4            5    10510.0      12629.0     13921.0      1770.0   
5            6     6665.0       5142.0      9972.0      1442.0   
6            7    13153.0      11869.0     17811.0      1542.0   
7            8     5882.0       9948.0     13315.0      1261.0   
8            9     7495.0      11589.0     13370.0      1090.0   
9           10     8233.0       7067.0     11400.0      1030.0   

   Items_Available       Parking Coupon_Category  Daily_Customer_Count  \
0           1961.0          Open           CAT B                   530   
1           1752.0  Not Provided           CAT B                   210   
2           1609.0  Not Provided

###  Display the last 5 entries of the dataset.(Hint- use function tail())

In [55]:
print("Last 5 entries:\n", df.tail(5))


Last 5 entries:
      Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available  Parking Coupon_Category  Daily_Customer_Count  \
927           1910.0  Covered           CAT C                  1080   
928           1663.0     Open           CAT A                   850   
929           1436.0     Open           CAT A                  1060   
930           1560.0     Open           CAT B                   770   
931           1429.0  Covered           CAT C                  1110   

     Store_Sales  
927        66390  
928        82080  
929        76440  
930        96610  
931        54340  


### How many rows and columns are present in the dataset? (Hint- Use function shape)

In [56]:
print("Shape of the dataset (rows, columns):", df.shape)

Shape of the dataset (rows, columns): (932, 10)


###  What are the different data types of the variables in the given dataset? (Hint- Use function info())

In [57]:
print("Data types of the variables:\n", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932 entries, 0 to 931
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Observation           932 non-null    int64  
 1   Dist_Taxi             919 non-null    float64
 2   Dist_Market           919 non-null    float64
 3   Dist_Metro            931 non-null    float64
 4   Store_Area            924 non-null    float64
 5   Items_Available       917 non-null    float64
 6   Parking               932 non-null    object 
 7   Coupon_Category       932 non-null    object 
 8   Daily_Customer_Count  932 non-null    int64  
 9   Store_Sales           932 non-null    int64  
dtypes: float64(5), int64(3), object(2)
memory usage: 72.9+ KB
Data types of the variables:
 None


**Or you can use below command as well**

# END